### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ricarsch** [lingyongyan/bootstrapping_pre-train#2]
The sample commands mentioned inside REAME document:

- python pretrain_self.py --out_model_file models/xxx1
- python pretrain_sup.py --input_model_file models/xxx1 --out_model_file models/xxx2

Both of the **"out_model_file"** option should be corrected as **"output_model_file"**

Cheers.

**Comment by lingyongyan** [comment]
thx, Appreciate for your pointing out.
